### ISSUE TITLE
¿Cómo debería ser el diseño del Homepage?

### ISSUE THREAD

**Issue by rodowi** [mxabierto/nom-nom-nom#1]
Acá nuestro primer saque:

![homepage](https://cloud.githubusercontent.com/assets/705860/6133171/bb89a524-b11d-11e4-8a7a-fd0470ebb2ea.png)

**Comment by rodowi** [comment]
¿qué opinan @emirhg @diegobeauroyre @simiographics?

**Comment by diegobeauroyre** [comment]
Uf se ve muy muy bien :tada: 

No sé si tengamos que usar Open Sans?

**Comment by rodowi** [comment]
El autor fue @simiographics 

El sketch está en https://www.dropbox.com/s/9xgubjliwuf398p/01%20-NOMS%20GOB%20it-01.sketch?dl=0

**Comment by diegobeauroyre** [comment]
:ok_hand:
