### ISSUE TITLE
Como usuario puedo ver el detalle de una NOM y sus documentos en el proyecto

### ISSUE THREAD

**Issue by rodowi** [mxabierto/nom-nom-nom#12]

**Comment by emirhg** [comment]
¿No es esta vista http://noms.dev.imco.org.mx/#/nom/NOM-001-CONAGUA-2011?

**Comment by rodowi** [comment]
sí sí, estaba abriendo issues para que quedara claro qué milestone es v1 y que se va para v2. Fue un acuerdo para discutir en la próxima reunión, no?

**Comment by emirhg** [comment]
Tengo mala memoria, cómo los issues fueron post v1 creia que eran cosas que
aún estaban pendientes.

2015-03-20 17:55 GMT-06:00 Rod Wilhelmy <notifications@github.com>:

> Closed #12 <https://github.com/mxabierto/nom-nom-nom/issues/12>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mxabierto/nom-nom-nom/issues/12#event-260916862>.
>



-- 
*Emir Herrera González* / Oficial de Tecnología
emir.herrera@imco.org.mx
+52 (55) 434471

-- 
* <http://imco.org.mx/indices/#!/competitividad_estatal_2014/introduccion>*
Instituto Mexicano para la Competitividad A.C.
Musset No.32, Polanco, CP11560. México D.F.

Twitter: @IMCOmx <http://twitter.com/imcomx> | Facebook: /IMCOmx 
<http://facebook.com/imcomx> | YouTube: /IMCOmexico 
<http://youtube.com/imcomexico>
